# Generated by Django 3.1.3 on 2022-03-20 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20220319_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='store.address'),
            preserve_default=False,
        ),
    ]
