# Generated by Django 3.1.3 on 2022-03-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20220319_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
