# Generated by Django 3.1.3 on 2022-04-03 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_productimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimages',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='productimages',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='productimages',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='productimages',
            name='image4',
        ),
    ]
