# Generated by Django 3.1.3 on 2022-04-03 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20220402_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimages',
            old_name='image',
            new_name='image0',
        ),
        migrations.AddField(
            model_name='productimages',
            name='image1',
            field=models.ImageField(default=23, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productimages',
            name='image2',
            field=models.ImageField(default=12, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productimages',
            name='image3',
            field=models.ImageField(default=12, upload_to=''),
            preserve_default=False,
        ),
    ]
