# Generated by Django 3.1.3 on 2022-04-03 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20220402_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='image0',
            field=models.ImageField(default='empty.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image1',
            field=models.ImageField(default='empty.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image2',
            field=models.ImageField(default='empty.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image3',
            field=models.ImageField(default='empty.png', upload_to=''),
        ),
    ]
